apiVersion: v1
kind: Service
metadata:
  name: seletor
  labels:
    app: private-reg
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30301
    name: registry
  selector:
    app: private-reg 
