apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  labels:
    app: private-reg
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30302
    name: registry
  selector:
    app: private-reg 
